services:
  # Nginx backend server
  nginx-backend:
    image: nginx:latest
    container_name: prestabanco-nginx-backend-container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./backend/backend.conf:/etc/nginx/nginx.conf 
    networks:
      - prestabanco-backend-network
    depends_on:
      - spring1
      - spring2
      - spring3

  # Nginx frontend server
  nginx-frontend:
    image: nginx:latest
    container_name: prestabanco-nginx-frontend-container
    restart: always
    ports:
      - "8070:8070"
    volumes:
      - ./frontend.conf:/etc/nginx/nginx.conf
    networks:
      - prestabanco-frontend-network
    depends_on:
      - react1
      - react2
      - react3

  # PostgreSQL service
  postgres:
    container_name: prestabanco-postgres-container
    image: postgres
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - prestabanco-postgres-volume:/var/lib/postgresql/data
    networks:
      - prestabanco-backend-network
    environment:
      POSTGRES_PASSWORD: 230902
    ports:
      - "5432:5432"

  # Spring backend services
  spring1:
    container_name: prestabanco-backend-container-1
    image: reii23/spring-image
    ports:
      - "8081:8080"
    environment:
      DB_HOST: prestabanco-postgres-container
      DB_PORT: 5432
      DB_NAME: prestabanco
      DB_USERNAME: postgres
      DB_PASSWORD: 230902
    networks:
      - prestabanco-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres

  spring2:
    container_name: prestabanco-backend-container-2
    image: reii23/spring-image
    ports:
      - "8082:8080"
    environment:
      DB_HOST: prestabanco-postgres-container
      DB_PORT: 5432
      DB_NAME: prestabanco
      DB_USERNAME: postgres
      DB_PASSWORD: 230902
    networks:
      - prestabanco-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres

  spring3:
    container_name: prestabanco-backend-container-3
    image: reii23/spring-image
    ports:
      - "8083:8080"
    environment:
      DB_HOST: prestabanco-postgres-container
      DB_PORT: 5432
      DB_NAME: prestabanco
      DB_USERNAME: postgres
      DB_PASSWORD: 230902
    networks:
      - prestabanco-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres

  # React frontend services
    react1:
    container_name: prestabanco-frontend-container-1
    image: reii23/prestabanco-frontend:latest
    ports:
      - "3001:3000"
    networks:
      - prestabanco-frontend-network
    deploy:
      restart_policy:
        condition: on-failure

    react2:
    container_name: prestabanco-frontend-container-2
    image: reii23/prestabanco-frontend:latest
    ports:
      - "3002:3000"
    networks:
      - prestabanco-frontend-network
    deploy:
      restart_policy:
        condition: on-failure

    react3:
    container_name: prestabanco-frontend-container-3
    image: reii23/prestabanco-frontend:latest
    ports:
      - "3003:3000"
    networks:
      - prestabanco-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  prestabanco-postgres-volume:
networks:
  prestabanco-backend-network:
  prestabanco-frontend-network:
