version: "3.0"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prestabanco-frontend
    ports:
      - "3000:3000"
    networks:
      - prestabanco-frontend-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - VITE_API_URL=http://localhost:8080/api

networks:
  prestabanco-frontend-network:
    driver: bridge
