version: "3.0"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prestabanco-frontend
    ports:
      - "3000:3000"
    networks:
      - prestabanco-network
    environment:
      - VITE_API_URL=http://backend:8080/api

  backend:
    image: reii23/spring-image
    container_name: prestabanco-backend
    ports:
      - "8080:8080"
    networks:
      - prestabanco-network

networks:
  prestabanco-network:
    driver: bridge
